import { CardItemProps } from "../../components/molecules/Card/CardItem";

export const dataSingleCompanies = {
  id: 'QLSKMDK',
  name: 'Hetic',
  type: 'Startup',
  pattern: '@hetic.net',
  employeesTotal: '90',
  created: '12/03/21',
  address: '16 Rue du Kelber, 75020 Paris',
  perimeter: '1km',
  emailAdmin: 'vico.roche@hetic.net',
  status: true,
  logo: 'https://source.unsplash.com/900x900/?food,gree,vegan,bio',
  employeesData: [
    {
      name: 'Victor Cantine',
      pattern: 'victorcantine@hetic.net',
      lastConnection: '22/07/2021'
    },
    {
      name: 'Victor Cantine',
      pattern: 'victorcantine@hetic.net',
      lastConnection: '22/07/2021'
    },
    {
      name: 'Victor Cantine',
      pattern: 'victorcantine@hetic.net',
      lastConnection: '22/07/2021'
    },
    {
      name: 'Victor Cantine',
      pattern: 'victorcantine@hetic.net',
      lastConnection: '22/07/2021'
    }
  ],
  longitude: '2.354768',
  latitude: '48.860589',
};

export const dataTableHead = [
  'Nom',
  'Type',
  'Pattern',
  'Effectif',
  'Crée le',
  'État'
];

export const dataAllCompanies = [
  {
    id: 'QLSKMDK',
    name: 'Title test',
    type: 'Startup',
    pattern: '@turning.net',
    numberOfEmployees: 23,
    creationDate: '12/03/21',
    status: true,
    longitude: '2.354768',
    latitude: '48.860589',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: true,
    longitude: '2.332595',
    latitude: '48.864371',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.292952',
    latitude: '48.868671',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: true,
    longitude: '2.397322',
    latitude: '48.87102',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.402886',
    latitude: '48.868671',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.369143',
    latitude: '48.853161',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.324768',
    latitude: '48.680589',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.322595',
    latitude: '48.764371',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.391322',
    latitude: '48.87802',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.412886',
    latitude: '48.849557',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.412886',
    latitude: '48.849557',
  },
  {
    id: 'QLSKMDK',
    name: 'Victor Cantine',
    type: 'Startup',
    pattern: '@turning.net',
    employeesTotal: 23,
    created: '12/03/21',
    status: false,
    longitude: '2.329143',
    latitude: '48.859161',
  },
];

export const fakeDataCompanies: CardItemProps[] = [
  {
    id: 1,
    center: [2.354768, 48.860589],
    zoom: 18,
    pitch: 20,
    type: 'business',
    price: '€',
    tags: ['africa', 'bar'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 2,
    center: [2.332595, 48.864371],
    zoom: 18,
    pitch: 20,
    type: 'business',
    price: '€€€',
    tags: ['africa'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 3,
    center: [2.292952, 48.87102],
    zoom: 18,
    pitch: 20,
    type: 'business',
    price: '€€',
    tags: ['burger', 'bar'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 4,
    center: [2.397322, 48.87102],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€',
    tags: ['burger', 'vegan', 'cosy', 'sushi', 'indien'],
    images: [
      'https://source.unsplash.com/300x400/?vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 5,
    center: [2.402886, 48.859557],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€',
    tags: ['bar'],
    images: [
      'https://source.unsplash.com/300x400/?food,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 6,
    center: [2.369143, 48.853161],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€€',
    tags: ['africa', 'bar'],
    images: [
      'https://source.unsplash.com/300x400/?vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 7,
    center: [2.324768, 48.680589],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€',
    tags: ['africa', 'bar'],
    images: [
      'https://source.unsplash.com/300x400/?green,vegan',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 8,
    center: [2.322595, 48.764371],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€€',
    tags: ['salade', 'cosy'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 9,
    center: [2.292952, 48.83102],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€',
    tags: ['burger', 'bar', 'salade'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 10,
    center: [2.391322, 48.87802],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€€',
    tags: ['burger'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 11,
    center: [2.412886, 48.849557],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€€',
    tags: ['bar', 'sushi', 'cosy'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
  {
    id: 12,
    center: [2.329143, 48.859161],
    zoom: 15.5,
    pitch: 20,
    type: 'business',
    price: '€€',
    tags: ['africa', 'bar'],
    images: [
      'https://source.unsplash.com/300x400/?food,gree,vegan,bio',
      'https://source.unsplash.com/1600x900/?food',
      'https://source.unsplash.com/1600x900/?food,snack,fastfood',
    ],
    title: 'Titre test',
    name: 'Chez vico',
    adress: '12 rue test',
    score: 8.6,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nisl tristique dignissim tellus malesuada enim, pharetra.',
    longitude: '2.383572',
    latitude: '48.868671',
  },
];
