sudo: required

services:
  - docker

language: node_js

node_js:
  - node

branches:
  only:
    - master
    - deployment

env:
  global:
    - PRIVATE_KEY_PATH=./devops/secrets/private_key

script:
  - openssl aes-256-cbc -K $encrypted_4987b30d526d_key -iv $encrypted_4987b30d526d_iv -in ./devops/secrets/secrets.tar.enc -out secrets.tar -d
  - tar xvf ./secrets.tar
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USERNAME/heticmadu-client-app:latest -f ./devops/docker/Dockerfile ./
  - docker push $DOCKER_USERNAME/heticmadu-client-app:latest
  - ssh-keyscan -H $EC2_URL
  - chmod -R 600 $PRIVATE_KEY_PATH
  - eval $(ssh-agent)
  - ssh-add $PRIVATE_KEY_PATH
  - scp -o StrictHostKeyChecking=no ./devops/docker/docker-compose.yml ubuntu@$EC2_URL:/home/ubuntu/docker-compose.client.yml
  - scp -o StrictHostKeyChecking=no ./devops/secrets/.env ubuntu@$EC2_URL:/home/ubuntu/.env
  - ssh -i $PRIVATE_KEY_PATH ubuntu@$EC2_URL 'bash -s' < ./devops/deploy.sh
  - rm $PRIVATE_KEY_PATH