version: '3.5'

services:
  client-app:
    env_file:
      - ../../../devops/dev/secrets/.env
    build:
      context: ../../..
      dockerfile: ./devops/dev/docker/Dockerfile
    container_name: heticmadu-client-app
    ports:
      - 4000:4000
    volumes:
      - ../../..:/home/node
